image: ubuntu:18.04

build:
  stage: build
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq -y install wget tar make git patch xz-utils gcc bc xxd gcc-aarch64-linux-gnu build-essential bison flex python3 python3-distutils python3-dev swig python python-dev kmod
    - mkdir proprietary_vendor_nvidia/ && cd proprietary_vendor_nvidia/
    - git init
    - git remote add -f origin https://gitlab.incom.co/CM-Shield/proprietary_vendor_nvidia/
    - git config core.sparseCheckout true
    - echo "t210/firmware/" >> .git/info/sparse-checkout
    - git pull origin lineage-17.0
    - cp -r t210/firmware/gm20b /lib/firmware
    - cp -r t210/firmware/tegra21x /lib/firmware/
    - cp t210/firmware/xusb/tegra21x_xusb_firmware /lib/firmware/
    - cd ../ && mkdir -p /build
  script:
    - export CROSS_COMPILE=aarch64-linux-gnu- && export ARCH=arm64 && export CPUS=$(nproc)
    - ./l4t_kernel_prep_rel32.sh
  artifacts:
    paths:
      - /build/Final/Image
      - /build/Final/tegra210-icosa.dtb
      - /build/Final/lib/
